language: python
python:
- 3.6
- 3.7
- 3.8
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: dbarroso
  password:
    secure: xfbyl+7EqXphy7DLIY1B9/IgecWX3IF0xKDnxJk3egJYKYvVT4thMGnBEAH4gKfVMU78LU6vyNr0g3kQT/AY1srRdG6gXjmUiwNQR/uwbpl3RBLFyRKUqiwNl/v3nFLmw/zmUhwtJKs1rVDqb7yvy6JzqhcBoFMNXSdf400QJzWzJS7VqMqXcdSUXHcPsVAzjYOWrKc0nuQsbFrYPwZNoskxzhxQfKTgZxtSEUCNLWWyQZv1xeywVq3HIjxwzP19b6phI14YnegQAtiPSQDRD+xYcL16lvWGIS+AW3K9Q8fk5UT7V8P41yarA0b0gL+rMlFTMpv+4zSSHus87R70EODC3LjYwOcGH81bw8Ctsm53/q7uPLJ8H4PDzc/No5MEbxsg0882CLLmkZXz35nGQQmvpv9DlyM4R3u2WhpFYxE/t/6uLOzhbt2QPcarZhrjJ/dkxN/H2xVuQJ1cM6+fG3MeTNI52n8kenl/97PSVcN7O+FZ2eGyVQOlNfVaPy3Qw57iSlMQWoUY7amh1/i488cXpLtt7fRFnB6bMeHKlxoh99DIH+pdRi25ltdAxQwLeitL6rCjYAEJqkKp3omTeV07+/oXB4L6ySVvFD/GZZy8H2Oi8ea75JOqyo9+WfsBT1sqsXIlCd12qHSiwANBiWira1T1GBUVXqkX5X6C8KY=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
- if [ $TRAVIS_TAG ]; then curl -X POST https://readthedocs.org/build/napalm; fi
